#!/bin/bash
#PBS -N scalability-test
#PBS -q cpu
#PBS -l select=1:ncpus=16:mpiprocs=16:host=cpu01
#PBS -l walltime=24:00:00
#PBS -o scalability.out
#PBS -e scalability.err

cd /tmp/nmpde-wave-equation/scripts

echo "Job started on $(date)"
echo "Node(s):"
cat "$PBS_NODEFILE"

apptainer exec ../../amsc_mk_2025.sif /bin/bash -c "source /u/sw/etc/bash.bashrc && module load gcc-glibc dealii && python scalability-test.py"

cp scalability-results.csv /home/u11177200/

echo "Job finished on $(date)"
