# -*- coding: utf-8 -*-
"""DISSIPATION_DISPERSION_ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mcqWwXdHnCekitx-LmjWAfsvoFcgK4F

# DISPERSION AND DISSIPATION ANALYSIS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

"""Loading a csv file from the Newmark simulation, which contain the solution over the time of the central node of the mesh (0.5, 0.5)."""

# Reading the csv file
csv_file = "001.csv"
csv_file2 = "overtime.csv"

df = pd.read_csv(csv_file, quotechar='"')
df.rename(columns=lambda x: x.strip('"'), inplace=True)

df2 = pd.read_csv(csv_file2, quotechar='"')
df2.rename(columns=lambda x: x.strip('"'), inplace=True)


timestep = df["Time"].values.astype(float)
u_num = df["avg(u)"].values.astype(float)


timestep2 = df2["Time"].values.astype(float)
u_num2 = df2["avg(u)"].values.astype(float)

"""The u solution is going to be fitted to the cos(pi * sqrt(2)) function, which is the exact solution of our temporal problem.

It is possible to appreciate that the function correspond and that neither dispersion nor dissipation is encountered here.
"""

# Time step of the simulation
dt = 0.001
omega_guess = np.sqrt(2)*np.pi
t = timestep * dt



def cos_fit_free(t, A, phi, omega):
    return A * np.cos(omega * t + phi)


#Newmark solution fit
popt, pcov = curve_fit(cos_fit_free, t, u_num, p0=[1.0, 0.0, omega_guess])
A_fit, phi_fit, omega_fit = popt
print(f"Newmark solution: Amplitude = {A_fit:.6f}, Phase = {phi_fit:.6f} rad, ω_num = {omega_fit:.6f} rad/s")

plt.figure(figsize=(10,4))
plt.plot(t, u_num, label="Newmark u(t)")
plt.plot(t, cos_fit_free(t, A_fit, phi_fit, omega_fit), 'r--', label=f"Cosine fit ω_num={omega_fit:.4f}")
plt.xlabel("Time [s]")
plt.ylabel("u")
plt.title("Newmark solution vs Cosine fit (ω free)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()


#CN solution fit
popt2, pcov2 = curve_fit(cos_fit_free, t, u_num2, p0=[1.0, 0.0, omega_guess])
A2, phi2, omega2 = popt2
print(f"CN solution: Amplitude = {A2:.6f}, Phase = {phi2:.6f} rad, ω_num = {omega2:.6f} rad/s")

plt.figure(figsize=(10,4))
plt.plot(t, u_num2, label="CN u2(t)")
plt.plot(t, cos_fit_free(t, A2, phi2, omega2), 'g--', label=f"Cosine fit ω_num={omega2:.4f}")
plt.xlabel("Time [s]")
plt.ylabel("u")
plt.title("CN solution vs Cosine fit (ω free)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""* Initial condition :  A1*sin(pi*x)*sin(2*pi*y) + A2*sin(2*pi*x)*sin(pi*y)"""

dt_bi = 0.0035

# Reading the csv file
csv_file3 = "twomodes.csv"
csv_file4 = "twomodes25.csv"

df_fine = pd.read_csv(csv_file3, quotechar='"')
df_fine.rename(columns=lambda x: x.strip('"'), inplace=True)

df_coarse = pd.read_csv(csv_file4, quotechar='"')
df_coarse.rename(columns=lambda x: x.strip('"'), inplace=True)

t_fine = df_fine["Time"].values * dt
u_num_fine = df_fine["avg(u)"].values.astype(float)

t_coarse = df_coarse["Time"].values * dt
u_num_coarse = df_coarse["avg(u)"].values.astype(float)

#exact pulsation
omega_guess = np.pi * np.sqrt(5)

#Dumping cosine

def damped_cos(t, A, phi, omega, alpha):
    return A * np.exp(-alpha * t) * np.cos(omega * t + phi)

#Fit fine solution

popt_fine, _ = curve_fit(damped_cos, t_fine, u_num_fine, p0=[1.0, 0.0, omega_guess, 0.0])
A_fine, phi_fine, omega_fine, alpha_fine = popt_fine
print("=== Fine mesh ===")
print(f"Amplitude = {A_fine:.6f}, Phase = {phi_fine:.6f} rad")
print(f"ω_num = {omega_fine:.6f} rad/s, α_num = {alpha_fine:.6e} 1/s")

#Fit coarse solution

popt_coarse, _ = curve_fit(damped_cos, t_coarse, u_num_coarse, p0=[1.0, 0.0, omega_guess, 0.0])
A_coarse, phi_coarse, omega_coarse, alpha_coarse = popt_coarse
print("\n=== Coarse mesh (N_el=50) ===")
print(f"Amplitude = {A_coarse:.6f}, Phase = {phi_coarse:.6f} rad")
print(f"ω_num = {omega_coarse:.6f} rad/s, α_num = {alpha_coarse:.6e} 1/s")


plt.figure(figsize=(10,4))
plt.plot(t_fine, u_num_fine, label="Numerical u(t) - fine mesh")
plt.plot(t_fine, damped_cos(t_fine, A_fine, phi_fine, omega_fine, alpha_fine), 'r--',
         label=f"Fit fine: ω={omega_fine:.4f}, α={alpha_fine:.2e}")
plt.xlabel("Time [s]")
plt.ylabel("u")
plt.title("Numerical solution vs Damped Cosine Fit (Fine Mesh)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,4))
plt.plot(t_coarse, u_num_coarse, label="Numerical u(t) - coarse mesh")
plt.plot(t_coarse, damped_cos(t_coarse, A_coarse, phi_coarse, omega_coarse, alpha_coarse), 'g--',
         label=f"Fit coarse: ω={omega_coarse:.4f}, α={alpha_coarse:.2e}")
plt.xlabel("Time [s]")
plt.ylabel("u")
plt.title("Numerical solution vs Damped Cosine Fit (Coarse Mesh N_el=25)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""* Using a dumping unimodal signal and evaluating dispersion and dissipation"""

csv_file5 = "smorzato.csv"

df_5 = pd.read_csv(csv_file5, quotechar='"')
df_5.rename(columns=lambda x: x.strip('"'), inplace=True)

Dt_5 = 0.00350
t = df_5["Time"].values.astype(float) * Dt_5
u_num_5= df_5["avg(u)"].values.astype(float)

# Point coordinate
x0 = 0.5
y0 = 0.5
n = 1
m = 1

#Parameter of exact solution
gamma_exact = 0.1
omega_exact = np.sqrt(2) * np.pi         # rad/s,
A_guess = 0.2                           # amplitude

# Dumped model
def damped_mode(t, A, gamma, omega):
    return A * np.exp(-gamma*t) * np.cos(omega*t) * np.sin(n*np.pi*x0) * np.sin(m*np.pi*y0)


#Fit of the numerical solution
p0 = [A_guess, 0.05, omega_exact]
params_opt, _ = curve_fit(damped_mode, t, u_num_5, p0=p0)
A_fit, gamma_fit, omega_fit = params_opt
u_fit = damped_mode(t, *params_opt)

# Dispersion and dissipation errors
num_diss = gamma_fit - gamma_exact
num_disp = omega_fit - omega_exact


print("=== FIT RESULTS ===")
print(f"A_fit = {A_fit:.5f}")
print(f"gamma_fit = {gamma_fit:.5f} rad/s")
print(f"Numerical dissipation = gamma_fit - gamma_exact = {num_diss:.5f}")
print(f"omega_fit = {omega_fit:.5f} rad/s ({omega_fit/(2*np.pi):.5f} Hz)")
print(f"Numerical dispersion = omega_fit - omega_exact = {num_disp:.5f} rad/s")

# RMS error
rms_error = np.sqrt(np.mean((u_num - u_fit)**2))
print(f"RMS error fit: {rms_error:.5f}")

# ---------- PLOT ----------
plt.figure(figsize=(10,5))
plt.plot(t, u_num, label="Numerical signal")
plt.plot(t, u_fit, '--', label="Dumped fit")
plt.xlabel("Time [s]")
plt.ylabel("u(t) in (x0,y0)")
plt.title("Numerical solution vs dumped fit model")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()